version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mysql-pt:
    image: mysql:8
    env_file:
      - ./backend/env/.${NODE_ENV}.env
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./backend/mysql:/var/lib/mysql
    networks:
      - app-tier
    profiles:
      - local

  redis-pt:
    image: bitnami/redis:latest
    env_file:
      - ./backend/env/.${NODE_ENV}.env
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-tier
    profiles:
      - local

  backend-pt:
    image: backend-pt
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    env_file:
      - ./backend/env/.${NODE_ENV}.env
    environment:
      - DB_BASE_URL=mysql
      - REDIS_BASE_URL=redis
      - NODE_ENV=${NODE_ENV}
    container_name: backend
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend/certs/:/dist/certs:ro
    networks:
      - app-tier
    depends_on: [mysql-pt, redis-pt]

  nginx-pt:
    image: nginx-pt
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV_NAME_ARG: ${NODE_ENV}
        HOST_URL_ARG: ${HOST_URL}
    env_file:
      - ./frontend/env/.${NODE_ENV}.env
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST_URL: ${HOST_URL}
      UPSTREAM_BACKEND: ${UPSTREAM_BACKEND}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    container_name: frontend
    ports:
      - '4000:443'
    volumes:
      - ./backend/certs/:/etc/nginx/certs/:ro
      - ./frontend/public:/public:ro
    networks:
      - app-tier
    depends_on: [mysql-pt, redis-pt, backend-pt]

  mysql-test:
    image: mysql:8
    env_file:
      - ./backend/env/.${NODE_ENV}.env
    container_name: mysql-test
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_TEST_PORT}:${DB_PORT}
    networks:
      - app-tier
    profiles:
      - test

  redis-test:
    image: bitnami/redis:latest
    env_file:
      - ./backend/env/.${NODE_ENV}.env
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    container_name: redis-test
    ports:
      - ${REDIS_TEST_PORT}:${REDIS_PORT}
    networks:
      - app-tier
    profiles:
      - test
