services:
  nginx-for-local:
    image: nginx:latest
    container_name: nginx-for-local
    env_file:
      - ./env/.env
    environment:
      REGISTRY_DOMAIN: ${REGISTRY_DOMAIN}
      MYSQL_DOMAIN: ${REGISTRY_DOMAIN}
      REDIS_DOMAIN: ${REGISTRY_DOMAIN}
    ports:
      - "443:443"
    volumes:
      - ./registry/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: on-failure
    networks:
      - pipe-timer-network

  registry:
    image: registry:2
    container_name: registry
    env_file:
      - ./env/.env
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry-cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/registry-key.pem
      REGISTRY_STORAGE_DELETE_ENABLED: true
    ports:
      - ${REGISTRY_PORT}:${REGISTRY_PORT}
    volumes:
      - ./registry/auth:/auth
      - ./certs:/certs
    restart: on-failure
    networks:
      - pipe-timer-network

networks:
  pipe-timer-network:
    driver: bridge
    name: pipe-timer-network
