#cloud-config
groups:
  - ubuntu: [root,sys]

users:
  - default
  - name: ubuntu
    shell: /bin/bash
    primary_group: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}
  - name: root
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
packages:
  - mysql-server
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - docker-compose-plugin

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce
  - usermod -aG docker $USER
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

write_files:
  - encoding: base64
    content: ${ssl_public_key}
    owner: root:root
    path: ${workdir}/certs/pipetimer.com.pem
    permissions: '0644'
  - encoding: base64
    content: ${ssl_private_key}
    owner: root:root
    path: ${workdir}/certs/pipetimer.com.key
    permissions: '0600'
