#cloud-config
groups:
  - ubuntu: [root,sys]

users:
  - default
  - name: ubuntu
    shell: /bin/bash
    primary_group: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}
  - name: root
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
packages:
  - mysql-server

write_files:
  - encoding: base64
    content: ${ssl_public_key}
    owner: root:root
    path: ${workdir}/certs/pipetimer.com.pem
    permissions: '0644'
  - encoding: base64
    content: ${ssl_private_key}
    owner: root:root
    path: ${workdir}/certs/pipetimer.com.key
    permissions: '0600'
