name: create-pull-request-staging
on:
  push:
    branches-ignore:
      - main
      - production
      - staging
      - cpr/**

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Sync branches to ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Reset branch
        run: |
          git fetch origin ${{ github.ref_name }}:${{ github.ref_name }} --update-head-ok
          git reset --hard ${{ github.ref_name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: cpr/${{ github.ref_name }}
          title: Sync ${{ github.ref_name }} to staging
          delete-branch: true
          signoff: true
          body: |
          labels: |
            staging
            autoPR
          token: ${{ secrets.PAT }}
