name: sync-prod
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  sync-prod:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Reset branch
        run: |
          git fetch origin main:main --update-head-ok
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: cpr/sync
          title: Sync ${{ github.ref_name }} to production
          delete-branch: true
          signoff: true
          body: |
          labels: |
            production
            autoPR
          token: ${{ secrets.PAT }}
